#!/bin/sh
# postinst script for securedrop-config

set -e
set -x

case "$1" in
    configure)

    # Ensure official Tor repo entry is removed, so that only FPF mirror is used.
    rm -f /etc/apt/sources.list.d/deb_torproject_org_torproject_org.list

    # Repoint tor repositories to FPF mirror
    apt_security_list="/etc/apt/security.list"
    if [ -f "$apt_security_list" ]; then
        sed -i 's/deb\.torproject\.org\/torproject\.org/tor-apt.freedom.press/g' "$apt_security_list"
    fi
    # uninstall vanilla kernels if installed. Need to use at because dpkg lock is active in postinst
    echo "sudo apt remove -y 'linux-image-generic-lts-xenial' 'linux-image-.*generic'" | at now + 1 hour
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
