---
# After installing securedrop-grsec, remove
# old generic kernels to avoid accidental
# boots into a less secure environment.
- name: Remove generic kernel packages.
  command: apt-get remove -y {{ item }}
  with_items:
    - linux-signed-generic
    - linux-signed-generic-lts-utopic
    - linux-signed-image-generic
    - linux-signed-image-generic-lts-utopic
    - linux-image-generic-lts-xenial
    - 'linux-image-.*generic'
    - 'linux-headers-.*'
  tags:
    - apt

- name: Mark GRUB2 as manually installed so its not removed.
  command: apt-mark manual grub-pc
  register: grubpc_manual_mark
  changed_when: "'grub-pc was already set to manually installed.' not in grubpc_manual_mark.stdout"
  tags:
    - apt
    - kernel
    - grub

- name: Clean old apt packages.
  command: apt-get -y autoremove
  register: apt_autoremove_all
  changed_when: "'The following packages will be REMOVED' in apt_autoremove_all.stdout"
  tags:
    - apt
